In [31]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [3]:
##laod the data set
df=pd.read_csv("Churn_Modelling.csv")
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [9]:
##preprocess the data
##crop the irrelevant colums

df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, errors='ignore')
df.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [13]:
##encode the categorical data
label_encoder_gender=LabelEncoder()
df['Gender']=label_encoder_gender.fit_transform(df['Gender'])
df

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [15]:
##onehot encode for geography column
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geography_encoded=onehot_encoder_geo.fit_transform(df[['Geography']])
geography_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [17]:
geo_feature_names = (
    onehot_encoder_geo.get_feature_names_out(['Geography'])
    if hasattr(onehot_encoder_geo, "get_feature_names_out")
    else onehot_encoder_geo.get_feature_names(['Geography'])
)
geo_feature_names

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [20]:
geo_encoded_df=pd.DataFrame(geography_encoded.toarray(), columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [26]:
##combibe all the columns 

df=pd.concat([df.drop('Geography', axis=1), geo_encoded_df], axis=1)
df.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [27]:
##sAVe the encoders and scaler for future use
with open('label_encoder_gender.pkl', 'wb') as f:
    pickle.dump(label_encoder_gender,f)

with open('onehot_encoder_geo.pkl', 'wb') as f:
    pickle.dump(onehot_encoder_geo,f)

In [28]:
df

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 13 columns]

In [34]:
##divided the data into independent and dependednt features
from sklearn.preprocessing import StandardScaler
x=df.drop('Exited', axis=1)
y=df['Exited']

#spliting the data into training and testing sets
X_train,X_test,y_train,y_test=train_test_split(x,y, test_size=0.2,random_state=42)

#3scaling
scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [35]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [36]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [37]:
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler,f)

##Implementing ANN model

In [41]:
##Implementing ANN model ##Implementing ANN model 

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [42]:
##Build our ANN model

model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)), #hidde layer 1
    Dense(32,activation='relu'), #hidden layer 2
    Dense(1,activation='sigmoid')  ##output layer ( binary output so we use the sigmoid activation function)
])

WARNING:tensorflow:From c:\projects\ANN\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [44]:
import tensorflow 
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [45]:
##compile the model
model.compile(optimizer=opt, loss="binary_crossentropy", metrics=["accuracy"])

In [47]:
##setup the tensorboard callback
log_dir = "logs/fit"+ datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)

In [48]:
##set up early stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [57]:
##train the model

history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test), epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3023 - accuracy: 0.8721 - val_loss: 0.3502 - val_accuracy: 0.8645
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3038 - accuracy: 0.8719 - val_loss: 0.3620 - val_accuracy: 0.8555
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3045 - accuracy: 0.8729 - val_loss: 0.3629 - val_accuracy: 0.8615
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3016 - accuracy: 0.8723 - val_loss: 0.3607 - val_accuracy: 0.8615
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.2949 - accuracy: 0.8721 - val_loss: 0.3777 - val_accuracy: 0.8535
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.2994 - accuracy: 0.8737 - val_loss: 0.3670 - val_accuracy: 0.8580

In [58]:
model.save('model.h5')

c:\projects\ANN\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [59]:
##load tensorboard
%load_ext tensorboard

In [64]:
%tensorboard --logdir logs/fit20260314-173811

Reusing TensorBoard on port 6006 (pid 30048), started 0:02:01 ago. (Use '!kill 30048' to kill it.)